### ISSUE TITLE
Cavestory Plus playable on the Linux vita os

### ISSUE THREAD

**Issue by CGG776** [xerpi/vita-baremetal-linux-loader#2]
Well this is probably stupid, but why not ask right? What i want to know for sure is this can, can i play games on the linux os on vita as a whole or is not ready for day to day use, if not i will play my pc games else where. Thanks again Xerpi for you're excellent contribution to the Vita homebrew scene as a whole.

**Comment by xerpi** [comment]
If it's available for ARM, and uses SDL but without OpenGL (just software rendering) then it might be possible using SDL's fbdev backend.
