### ISSUE TITLE
Loader modification for another kernel

### ISSUE THREAD

**Issue by DvaMishkiLapa** [xerpi/vita-baremetal-linux-loader#5]
Good afternoon! 
If I compile a kernel which is different from [your kernel for PS Vita](https://github.com/xerpi/linux_vita) (for example, your variant, merged with [kernel 6.3](https://github.com/torvalds/linux/tree/v6.3)) do I need to change something in the code of this loader project? 

For example, the `dtb` and kernel load addresses.

**Comment by xerpi** [comment]
In theory, the loader should work without any changes.
To have early print to debug problems, I recommend using UART https://wiki.henkaku.xyz/vita/UART_Console#UART0
